### ISSUE TITLE
Refactor all configuration into a yaml file

### ISSUE THREAD

**Issue by iamjoemccormick** [iamjoemccormick/gitstats#1]
Move away from hard coding anything, notably desired endpoints. Example configuration file: 

```yaml
- GitHub:
    headers:
      Accept: "application/vnd.github.v3+json"  
    base: "https://api.github.com/repos/"
    repos:
      - user/repo
    endpoints: 
      Clones: /traffic/clones
      PopularPaths: /popular/paths
      PopularReferrers: /popular/referrers
      Views: /traffic/views
```
